# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  image: latest

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
