site_name: stglance
site_description: `stglance` is a small collection of `streamlit` widgets (for machine learning) that you can include in your streamlit app.
site_author: Soumendra Dhanee

repo_url: https://github.com/soumendra/stglance
edit_uri: ""

theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python

nav:
  - Home: index.md
  - User Guide:
      - Getting started: user-guide/getting-start.md
  - About:
      - Release Notes: about/release-notes.md
      - Contributing: about/contributing.md
      - License: about/license.md

extra_css:
  - css/extra.css

markdown_extensions:
  - toc:
      permalink: 
  - admonition
  - def_list
  - mdx_gh_links:
      user: soumendra
      repo: stlearn

copyright: Copyright &copy; 2021 <a href="https://twitter.com/dataBiryani">Soumendra Dhanee</a>
google_analytics: ["UA-2688259-1", "stlearn"]

plugins:
  - search
